export const SELL_MODAL_OPEN = "SELL_MODAL_OPEN";
export const SELL_MODAL_CLOSE = "SELL_MODAL_CLOSE";

export const INVOICE_MODAL_OPEN = 'INVOICE_MODAL_OPEN';
export const INVOICE_MODAL_CLOSE = 'INVOICE_MODAL_CLOSE';

export const ADD_INVOICE_PRODUCT = 'ADD_INVOICE_PRODUCT';
export const DELETE_INVOICE_PRODUCT = 'DELETE_INVOICE_PRODUCT';

export const CLEAR_INVOICE_PRODUCT = 'CLEAR_INVOICE_PRODUCT';

export const ERROR_INVOICE_PRODUCT = 'ERROR_INVOICE_PRODUCT';
export const ERROR_INVOICE_PRODUCT_FALSE = 'ERROR_INVOICE_PRODUCT_FALSE';

