export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SET_LOADING = 'SET_LOADING';

export const GET_CATEGORY_AND_PRODUCTS = "GET_CATEGORY_AND_PRODUCTS";
export const GET_NOTIFICATION = "GET_NOTIFICATION";

export const SET_SATYSH_STATUS = "SET_SATYSH_STATUS"
export const SET_SATYSH_ADD_STATUS = "SET_SATYSH_ADD_STATUS"
export const SET_EDITNIG_ID = "SET_EDITNIG_ID";
export const CLEAR_EDITING_ID = "CLEAR_EDITING_ID";

export const ADD_TO_INVOICE_LIST = "ADD_TO_INVOICE_LIST";
export const EDITING_INVOICE_LIST = "EDITING_INVOICE_LIST";
export const DELETE_IN_INVOICE_LIST = "DELETE_IN_INVOICE_LIST";
export const CLEAR_INVOICE_LIST = "CLEAR_INVOICE_LIST";

export const GET_SOLD_LIST = "GET_SOLD_LIST";
export const SET_SOLD_ROW_VIEW = "SET_SOLD_ROW_VIEW"
export const CLOSE_SOLD_ROW_VIEW = "CLOSE_SOLD_ROW_VIEW"

export const SET_SIDE_BAR = "SET_SIDE_BAR";

export const GET_STOCK_LIST = "GET_STOCK_LIST";
export const TRANSFER_FORM_OPEN = "TRANSFER_FORM_OPEN"
export const GET_TRANSFER_IN_LIST = "GET_TRANSFER_IN_LIST";
export const GET_TRANSFER_OUT_LIST = "GET_TRANSFER_OUT_LIST";
export const SET_TRANSFER_LIST_PROD = "SET_TRANSFER_LIST_PROD";
export const CLEAR_TRANSFER_LIST_PROD = "CLEAR_TRANSFER_LIST_PROD";
export const INPUT_TRANSFER_STATUS = "INPUT_TRANSFER_STATUS";

export const GET_STOCK_PRODUCTS = 'GET_STOCK_PRODUCTS';